AWSTemplateFormatVersion: '2010-09-09'
Description: Secure DevSecOps Pipeline - S3, DynamoDB, Lambda, IAM

Resources:

  # Bucket S3 pour stockage sécurisé avec journalisation et blocage des accès publics
  S3LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LoggingBucket  # peut être un bucket de logs séparé
        LogFilePrefix: logs/

  # Exemple de table DynamoDB
  SecureVaultTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SecureVault
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  # Lambda Function exemple
  SecureVaultLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SecureVaultFunction
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3LoggingBucket
          TABLE_NAME: !Ref SecureVaultTable
      Code:
        S3Bucket: my-lambda-code-bucket
        S3Key: secure-vault.zip

  # Role IAM pour Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SecureVaultLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
