AWSTemplateFormatVersion: '2010-09-09'
Description: Secure DevSecOps Vault - Infrastructure 100% Compliant (Least Privilege)

Resources:
  # 1. Clé KMS Maître
  SecureVaultKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Master Key for SecureVault Encryption"
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"

  # 2. Dead Letter Queue
  SecureVaultDLQ:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: !Ref SecureVaultKMSKey

  # 3. Bucket S3 Sécurisé (Données)
  MySecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref SecureVaultKMSKey
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LoggingBucket
        LogFilePrefix: access-logs/

  # 4. Bucket de Logs (Séparé)
  # checkov:skip=CKV_AWS_18:Le bucket de logs ne doit pas se loguer lui-même (boucle infinie)
  S3LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      # CORRECTION CHECKOV 21 : On active le versioning ici aussi
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # 5. Table DynamoDB
  MyMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "securedocvault-metadata-${AWS::AccountId}"
      AttributeDefinitions:
        - AttributeName: file_id
          AttributeType: S
      KeySchema:
        - AttributeName: file_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref SecureVaultKMSKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # 6. Rôle IAM (Restreint)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecureVaultAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: 
                  - !Sub "${MySecureBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt MyMetadataTable.Arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt SecureVaultKMSKey.Arn
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt SecureVaultDLQ.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # 7. Fonction Lambda
  UploadFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: securedocvault-upload-logic
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      KmsKeyArn: !GetAtt SecureVaultKMSKey.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref MySecureBucket
          TABLE_NAME: !Ref MyMetadataTable
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return "Security Fixed"
      DeadLetterConfig:
        TargetArn: !GetAtt SecureVaultDLQ.Arn
      ReservedConcurrentExecutions: 5
      TracingConfig:
        Mode: Active

Outputs:
  LambdaName:
    Value: !Ref UploadFunction
  BucketName:
    Value: !Ref MySecureBucket